AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GetConnectionSource:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: python3.6
      Handler: index.lambda_handler
      CodeUri: ./src
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /connectionsource
            Method: get
